on:
  push:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lib-net
        uses: actions/checkout@v3
        with:
          repository: voidbytes/rfu-net-lib
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: lib-net
          ref: master
     # - uses: actions/setup-go@v2
      #  with:
       #   go-version: "1.18"
      - name: Build executable file
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          prefix: rfu-net-lib
          targets: windows-10.0/amd64, windows-10.0/386 #,linux/amd64,linux/386,linux/arm64,darwin-10.16/arm64,darwin-10.16/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w 
          buildmode: default
          working_dir: ${{ github.workspace }}/lib-net
    
      - name: Build c-shared-lib file
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build/lib
          prefix: rfu-net-shared-lib
          targets: windows-10.0/amd64, windows-10.0/386 #,linux/amd64,linux/386,linux/arm64,darwin-10.16/arm64,darwin-10.16/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w 
          buildmode:  c-shared
          working_dir: ${{ github.workspace }}/lib-net                
      - name: Upload PE artifact
        uses: actions/upload-artifact@v3
        with:
          name: PE-artifact
          path: |
            ${{ github.workspace }}/lib-net/build/**/*
            !${{ github.workspace }}/lib-net/build/lib/**/* 
      - name: Upload lib artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lib-artifact
          path: ${{ github.workspace }}/lib-net/build/lib/**/*                 
      - name: Archive file
        run:  tar cvf $GITHUB_WORKSPACE/c-archive.tar -C $GITHUB_WORKSPACE/lib-net/build/lib .
        if: startsWith(github.ref, 'refs/tags/') 
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          files: |
            ${{ github.workspace }}/c-archive.tar
            ${{ github.workspace }}/lib-net/build/rfu-net-lib-windows-10.0-amd64.exe 
            ${{ github.workspace }}/lib-net/build/rfu-net-lib-windows-10.0-386.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}