on: 
  push
name: go Build
jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [386, amd64, arm64]
    steps:
      - name: Checkout lib-net
        uses: actions/checkout@v3
        with:
          repository: voidbytes/rfu-net-lib
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          ref: dev
      - name: Build c-shared-lib file
        run: |
          $env:CGO_ENABLED = 1
          $env:GOOS = 'windows'
          $env:GOARCH = ${{ matrix.platform }}
          go build -buildmode=c-shared -x -v -ldflags "-s -w" -o  libNetwork-${{ matrix.platform }}.dll 
      - name: Upload lib artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lib-artifact
          path: ${{ github.workspace }}/lib-net/build/lib/**/*
      - name: Archive file
        run: tar cvf $GITHUB_WORKSPACE/c-archive.tar -C $GITHUB_WORKSPACE/lib-net/build/lib .
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/c-archive.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}