on:
  push
name: go Build arm64
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["arm64"]
    steps:
      - name:  download llvm-mingw
        uses: dsaltares/fetch-gh-release-asset@master
        with:
           repo: 'mstorsjo/llvm-mingw'
           version: 'tags/20220906'
           file: 'llvm-mingw-20220906-msvcrt-ubuntu-18.04-x86_64.tar.xz'
           token: ${{ secrets.GH_PAT }}

      - name: Set up  tools
        run: |
          tar -xf llvm-mingw-20220906-msvcrt-ubuntu-18.04-x86_64.tar.xz
          cd llvm-mingw-20220906-msvcrt-ubuntu-18.04-x86_64.tar.xz/bin
          export PATH=$PATH:$(pwd)
      - name: Checkout lib-net
        uses: actions/checkout@v3
        with:
          repository: voidbytes/rfu-net-lib
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          ref: dev
      - name: Build c-shared-lib file
        run: |
          export CC="aarch64-w64-mingw32-gcc"
          export CXX="aarch64-w64-mingw32-g++"
          export GOOS="windows"
          export GOARCH= '${{ matrix.platform }}'
          export CGO_ENABLED="1"
          go build -buildmode=c-shared -x -v -ldflags "-s -w" -o libNetwork-${{ matrix.platform }}.dll .
      - name: Upload lib artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lib-artifact
          path: ${{ github.workspace }}/lib-net/build/lib/**/*
      - name: Archive file
        run: tar cvf $GITHUB_WORKSPACE/c-archive.tar -C $GITHUB_WORKSPACE/lib-net/build/lib .
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/c-archive.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
